### ISSUE TITLE
`useMeasure` types fail with the `@types/react` package version `17.0.41`

### ISSUE THREAD

**Issue by spirosikmd** [streamich/react-use#2305]
**What is the current behavior?**

The `useMeasure` types fail with the `@types/react` package version `17.0.41`.

**Steps to reproduce it and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have extra dependencies other than `react-use`. Paste the link to your [JSFiddle](https://jsfiddle.net) or [CodeSandbox](https://codesandbox.io) example below:**

https://codesandbox.io/s/broken-hooks-ps75vr?file=/src/App.tsx

**What is the expected behavior?**

The project compiles correctly!

**A little about versions:**  
- _OS_: Mac OSX 12.3
- _Browser (vendor and version)_: Safari 15.4
- _React_: 17.0.2
- _`react-use`_: 17.3.2
- _Did this worked in the previous package version?_ No

**Comment by sangdth** [comment]
I have similar type error:
`Type UseMeasurableRef<HTMLDivElement> is not assignable to type LegacyRef<HTMLDivElement> | undefined`

**Comment by bradennapier** [comment]
Also having this issue

**Comment by spirosikmd** [comment]
Version `17.0.42` of `@types/react` fixes the issue for me.

**Comment by SKADaddy** [comment]
i think the reason is this UseMeasureRef type
 `export type UseMeasureRef<E extends Element = Element> = (element: E) => void;`
the Element can be null just fix the type like this 
`export type UseMeasureRef<E extends Element = Element> = (element: E | null) => void;` the error will gone

**Comment by spirosikmd** [comment]
Thank you for your input @SKADaddy!

The issue is fixed with `17.0.42` of `@types/react` so we can close this issue!

**Comment by stefee** [comment]
This issue has returned in a newer version of React types, possibly due to https://github.com/DefinitelyTyped/DefinitelyTyped/pull/59395. I think @SKADaddy's suggestion is needed here.

**Comment by ronaldruzicka** [comment]
Should we reopen this issue? Because I still have it with these versions. I even tried `@types/react` version `17.0.42` but it was still not working.
```
"@types/react": "^17.0.48"
"react-use": "^17.4.0"
```

**Comment by ronaldruzicka** [comment]
I take it back, it works if you use generic with `useMeasure`

```
const [ref, { width }] = useMeasure<HTMLDivElement>();
```
